name: Build and Publish Add-on

on:
  push:
    branches:
      - main
    paths:
      - 'ruuvibridge/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: ./ruuvibridge
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/ruuvibridge:latest
