name: "RuuviBridge hassio add-on"
version: "25.10.26.7"
slug: "ruuvibridge"
description: "Bridge for RuuviTag sensor data.."
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
init: false
map:
  - config:rw
ports:
  8883/tcp: 8883
  8081/tcp: 8081
  8080/tcp: 8080
  8585/tcp: 8585
options:
  gateway_polling_enabled: false
  gateway_url: "http://ip.or.hostname.of.the.gateway"
  gateway_bearer_token: ""
  gateway_interval: "10s"

  mqtt_listener_enabled: false
  mqtt_listener_broker_url: "tcp://ip.or.hostname:1883"
  mqtt_listener_client_id: "RuuviBridgeListener"
  mqtt_listener_username: "ruuvibridge"
  mqtt_listener_password: "ruuvipassword"
  mqtt_listener_topic_prefix: "ruuvi"
  mqtt_listener_lwt_topic: ""
  mqtt_listener_lwt_online_payload: '{"state":"online"}'
  mqtt_listener_lwt_offline_payload: '{"state":"offline"}'

  http_listener_enabled: false
  http_listener_port: 8080

  influxdb_enabled: false
  influxdb_url: "http://localhost:8086"
  influxdb_auth_token: "changethis"
  influxdb_org: ""
  influxdb_bucket: "ruuvi"
  influxdb_measurement: "ruuvi_measurements"

  prometheus_enabled: false
  prometheus_port: 8081
  prometheus_prefix: "ruuvi"

  mqtt_publisher_enabled: false
  mqtt_publisher_broker_url: "tcp://ip.or.hostname:1883"
  mqtt_publisher_client_id: "RuuviBridgePublisher"
  mqtt_publisher_username: "ruuvibridge"
  mqtt_publisher_password: "ruuvipassword"
  mqtt_publisher_topic_prefix: "ruuvibridge"
  mqtt_publisher_publish_raw: false
  mqtt_publisher_lwt_topic: ""
  mqtt_publisher_lwt_online_payload: '{"state":"online"}'
  mqtt_publisher_lwt_offline_payload: '{"state":"offline"}'
  mqtt_publisher_homeassistant_discovery_prefix: "homeassistant"

  log_type: "structured"
  log_level: "info"
  log_timestamps: true
  debug: false

schema:
  gateway_polling_enabled:
    type: boolean
  gateway_url:
    type: string
  gateway_bearer_token:
    type: password
  gateway_interval:
    type: string

  mqtt_listener_enabled:
    type: boolean
  mqtt_listener_broker_url:
    type: string
  mqtt_listener_client_id:
    type: string
  mqtt_listener_username:
    type: string
  mqtt_listener_password:
    type: password
  mqtt_listener_topic_prefix:
    type: string
  mqtt_listener_lwt_topic:
    type: string
  mqtt_listener_lwt_online_payload:
    type: string
  mqtt_listener_lwt_offline_payload:
    type: string

  http_listener_enabled:
    type: boolean
  http_listener_port:
    type: integer

  influxdb_enabled:
    type: boolean
  influxdb_url:
    type: string
  influxdb_auth_token:
    type: password
  influxdb_org:
    type: string
  influxdb_bucket:
    type: string
  influxdb_measurement:
    type: string

  prometheus_enabled:
    type: boolean
  prometheus_port:
    type: integer
  prometheus_prefix:
    type: string

  mqtt_publisher_enabled:
    type: boolean
  mqtt_publisher_broker_url:
    type: string
  mqtt_publisher_client_id:
    type: string
  mqtt_publisher_username:
    type: string
  mqtt_publisher_password:
    type: password
  mqtt_publisher_topic_prefix:
    type: string
  mqtt_publisher_publish_raw:
    type: boolean
  mqtt_publisher_lwt_topic:
    type: string
  mqtt_publisher_lwt_online_payload:
    type: string
  mqtt_publisher_lwt_offline_payload:
    type: string
  mqtt_publisher_homeassistant_discovery_prefix:
    type: string

  log_type:
    type: string
    options:
      - structured
      - json
  log_level:
    type: string
    options:
      - trace
      - debug
      - info
      - warn
      - error
      - fatal
      - panic
  log_timestamps:
    type: boolean
  debug:
    type: boolean
# image: "ghcr.io/oggali/ruuvibridge-{arch}"
