name: "RuuviBridge hassio add-on"
version: "25.10.28.4"
slug: "ruuvibridge"
description: "Bridge for RuuviTag sensor data.."
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
init: false
map:
#  - config:rw
  - addon_config:rw
#  - homeassistant_config:rw
  - all_addon_configs:rw
ports:
  8883/tcp: 8883
  8081/tcp: 8081
  8080/tcp: 8080
  8585/tcp: 8585
options:
  gateway_polling_enabled: false
  gateway_url: "http://ip.or.hostname.of.the.gateway"
  gateway_bearer_token: ""
  gateway_interval: "10s"

  mqtt_listener_enabled: false
  mqtt_listener_broker_url: "tcp://ip.or.hostname:1883"
  mqtt_listener_client_id: "RuuviBridgeListener"
  mqtt_listener_username: "ruuvibridge"
  mqtt_listener_password: "ruuvipassword"
  mqtt_listener_topic_prefix: "ruuvi"
  mqtt_listener_lwt_topic: ""
  mqtt_listener_lwt_online_payload: "{\"state\":\"online\"}"
  mqtt_listener_lwt_offline_payload: "{\"state\":\"offline\"}"

  http_listener_enabled: false
  http_listener_port: 8080

  influxdb_enabled: false
  influxdb_url: "http://localhost:8086"
  influxdb_auth_token: "changethis"
  influxdb_org: ""
  influxdb_bucket: "ruuvi"
  influxdb_measurement: "ruuvi_measurements"

  prometheus_enabled: false
  prometheus_port: 8081
  prometheus_prefix: "ruuvi"

  mqtt_publisher_enabled: false
  mqtt_publisher_broker_url: "tcp://ip.or.hostname:1883"
  mqtt_publisher_client_id: "RuuviBridgePublisher"
  mqtt_publisher_username: "ruuvibridge"
  mqtt_publisher_password: "ruuvipassword"
  mqtt_publisher_topic_prefix: "ruuvibridge"
  minimum_interval: "10s"
  mqtt_publisher_publish_raw: false
  mqtt_publisher_lwt_topic: ""
  mqtt_publisher_lwt_online_payload: "{\"state\":\"online\"}"
  mqtt_publisher_lwt_offline_payload: "{\"state\":\"offline\"}"
  mqtt_publisher_homeassistant_discovery_prefix: "homeassistant"

  # Extra processing of the values

  # Extended values are enabled by default but can be disabled by changing extended_values to false
  processing_extended_values: true
  # Filter which devices are considered. Valid options:
  # none - no filtering is done, all devices are processed (default)
  # named - only devices which have a name configured will be processed
  # allowlist - only mac addresses listed in filter_list will be processed
  # denylist - mac addresses listed in filter_list will be skipped
  processing_filter_mode: none
  # List of mac addresses to allow or deny if filter_mode is either allowlist or denylist
#    filter_list:
#      - FFEEDDCCBBAA
#      - F0E1D2C3B4A5
  # You can disable specific formats here, for example if you are able to receive format E1 you should
  # disable format 6, as it's redundant in that case (E1 requires bluetooth 5 compatible hardware, for
  # example the official Ruuvi Gateway).
  processing_disable_formats:
  #- "6"
  # Flag to include unofficial data in the measurements. This is undocumented data that is included in some measurements sent by certain revisions of Ruuvi Air
  processing_include_unofficial: false

  log_type: "structured"
  log_level: "info"
  log_timestamps: true
  # Whether to include the log caller in the logs. This will increase the size of logs but it helps in troubleshooting in some cases
  with_caller: false
  debug: false

schema:
  gateway_polling_enabled: "bool"
  gateway_url: "str"
  gateway_bearer_token: "password"
  gateway_interval: "str"

  mqtt_listener_enabled: "bool"
  mqtt_listener_broker_url: "str"
  mqtt_listener_client_id: "str"
  mqtt_listener_username: "str"
  mqtt_listener_password: "password"
  mqtt_listener_topic_prefix: "str"
  mqtt_listener_lwt_topic: "str"
  mqtt_listener_lwt_online_payload: "str"
  mqtt_listener_lwt_offline_payload: "str"

  http_listener_enabled: "bool"
  http_listener_port: "int"

  influxdb_enabled: "bool"
  influxdb_url: "str"
  influxdb_auth_token: "password"
  influxdb_org: "str"
  influxdb_bucket: "str"
  influxdb_measurement: "str"

  prometheus_enabled: "bool"
  prometheus_port: "int"
  prometheus_prefix: "str"

  mqtt_publisher_enabled: "bool"
  mqtt_publisher_broker_url: "str"
  mqtt_publisher_client_id: "str"
  mqtt_publisher_username: "str"
  mqtt_publisher_password: "password"
  mqtt_publisher_topic_prefix: "str"
  minimum_interval: "str"
  mqtt_publisher_publish_raw: "bool"
  mqtt_publisher_lwt_topic: "str"
  mqtt_publisher_lwt_online_payload: "str"
  mqtt_publisher_lwt_offline_payload: "str"
  mqtt_publisher_homeassistant_discovery_prefix: "str"

  processing_extended_values: "bool"
  processing_filter_mode: "list(none|named|allowlist|denylist)"
  processing_disable_formats: "str"
  processing_include_unofficial: "bool"

  log_type: "list(structured|json)"
  log_level: "list(trace|debug|info|warn|error|fatal|panic)"
  log_timestamps: "bool"
  with_caller: "bool"
  debug: "bool"
# image: "ghcr.io/oggali/ruuvibridge-{arch}"
