name: Herrfors Session Fetcher
version: "2025.11.10.10"
slug: herrfors_selenium
description: "Fetch Herrfors session token using headless Chrome + Selenium at scheduled times."
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
init: false
homeassistant_api: true
host_network: true


options:
  email: ""
  password: ""
  timezone: "UTC"
  refresh_window_start: "05:00"
  refresh_window_end: "18:00"
  check_interval: 3600   # seconds between schedule checks
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
  run_immediately_on_start: true

schema:
  email: str
  password: password
  timezone: str
  refresh_window_start: str
  refresh_window_end: str
  check_interval: int
  user_agent: str
  run_immediately_on_start: bool

map:
  - share:rw

ports:
  8126/tcp: null

ingress: false

resources: []

environment:
  PUID: "0"
  PGID: "0"